### ISSUE TITLE
pandoc-citeproc missing on clang-asan

### ISSUE THREAD

**Issue by ms609** [gaborcsardi/rhub2#17]
I'm testing a package using the default `linux-containers: ` block in [`rhub.yaml`](https://github.com/ms609/TreeDist/blob/rhub.yaml/.github/workflows/rhub.yaml) (except with an `extra-packages:` parameter per r-hub/rhub2#11)

A run on the valgrind container succeeds; but the clang-asan action [fails](https://github.com/ms609/TreeDist/actions/runs/7929485242/job/21649811061) with the error "Could not find executable pandoc-citeproc".

I would like to compile the vignettes during the check, so as to identify any memory leaks that occur in vignette code but not package examples or tests.  However, it's not necessary to generate PDFs from the generated markdown files.

Can this be done, and if so, how do I need to configure my `rhub.yaml` file?

NB this follows on from our discussion at r-hub/rhub#582 – I thought I'd open a separate issue as I'm starting to understand how the differences in configurations affect different platforms.

**Comment by gaborcsardi** [comment]
Yeah, added some config to skip building vignettes in `R CMD build`, but then unfortunately there'll be no vignettes in the built source package, so the vignette code is no checked.

So this is clearly not ideal. I'll add some code to the check (or deps?) action to install tinytex automatically if your package has PDF vignettes....

**Comment by ms609** [comment]
Thanks – I tried this, but the `setup-pandoc` script relies on `sudo`, which is unavailable in clang-asan & valgrind:

[clang-asan](https://github.com/ms609/TreeDist/actions/runs/7959696260/job/21727190593#step:3:8)
Failed to install pandoc: Unable to locate executable file: sudo.
[valgrind](https://github.com/ms609/TreeDist/actions/runs/7959696260/job/21727191062#step:3:10)
Failed to install pandoc: The process '/usr/bin/sudo' failed with exit code 1

**Comment by gaborcsardi** [comment]
Right, you can install `sudo` first.

**Comment by ms609** [comment]
Thanks – I hadn't thought of sudo as something that could be installed separately, which I guess outs me as a linux novice!

I've had to perform a bit of logic to `apt-get install` sudo and run the setup-pandoc script only on the clang-asan instance (which runs ubuntu) – but not on valgrind (which runs fedora, thus doesn't support the apt-get call here or in setup-pandoc@v2)

```yml
      - name: Check distribution
        run: |
          echo "::set-output name=distribution::$(awk -F= '/^ID=/{print $2}' /etc/os-release)"
        id: check_distribution
      - name: apt-get install sudo (Ubuntu, for clang-asan)
        run: apt-get install sudo
        if: ${{ steps.check_distribution.outputs.distribution == 'ubuntu' }}
      - uses: r-lib/actions/setup-pandoc@v2
        if: ${{ steps.check_distribution.outputs.distribution != 'fedora' }}
```

Unfortunately a consequence of not compiling PDFs of the vignettes during the valgrind run is that rhub-run-check [fails with warnings](https://github.com/ms609/TreeDist/actions/runs/7962088039/job/21734763180):

```
❯ checking files in ‘vignettes’ ... WARNING
  Files in the 'vignettes' directory but no files in 'inst/doc':
    ‘Batch1.svg’ [...] ‘Using-TreeDist.Rmd’

❯ checking package vignettes ... WARNING
  Directory 'inst/doc' does not exist.
  Package vignettes without corresponding single PDF/HTML:
    ‘compare-treesets.Rmd’
[...]
```
