### ISSUE TITLE
Install TinyTeX

### ISSUE THREAD

**Issue by gaborcsardi** [gaborcsardi/rhub2#3]
On demand. Maybe needs a config option? The TeXlive packages also need a config option. 

These config options (and others as well) could default to some `Config/GHA` entries in `DESCRIPTION`.

**Comment by ms609** [comment]
This was a roadblock for one of my packages that used `pdflatex` to compile vignettes.
After much heartache I found an existing action that did all the heavy lifting for win, mac and linux.
Adding the below to `rhub.yaml` did the trick:

```yaml
- name: Setup TeX Live
  uses: teatimeguest/setup-texlive-action@v3
  with:
    packages: scheme-basic
```
